### ISSUE TITLE
Информация о заканчивающейся лицензии

### ISSUE THREAD

**Issue by Takohashi** [ilyahoilik/invision-localization#177]
Ключ: license_renewal_soon
Текущий перевод: `Ваша лицензия истечет через {!# [*1:# день][*2:# дня][*3:# дня][*4:# дня][*11:# дней][*12:# дней][*13:# дней][*14:# дней][1:завтра][2:послезавтра][?:# дней]}.`

С «завтра/послезавтра» получается некорректное предложение:

![Снимок экрана 2019-04-03 в 0 33 49](https://user-images.githubusercontent.com/9580166/55438116-6c84fe80-55a9-11e9-82fa-4cdefb939ced.png)

**Comment by SPEC1AL1ST** [comment]
Предлагаю:
<word key="license_renewal_soon" js="0">Ваша лицензия истечет через {!# [*1:# день][*2:# дня][*3:# дня][*4:# дня][*11:# дней][*12:# дней][*13:# дней][*14:# дней][1:# день][2:# дня][?:# дней]}.</word>

**Comment by Takohashi** [comment]
Только какой смысл для 11, 12, 13 и 14 указывать отдельные значения, если там везде «дней»?

**Comment by ilyahoilik** [comment]
@Takohashi, если не указывать значение для чисел, заканчивающихся на *11, *12, *13 и *14, то они будут использовать значения из чисел, заканчивающихся на *1, *2, *3 и *4, которые являются неверными.
