### ISSUE TITLE
err_password_strength

### ISSUE THREAD

**Issue by SPEC1AL1ST** [ilyahoilik/invision-localization#185]
<word key="err_password_strength" js="1"> - значение повторяется два раза в документе

**Comment by ilyahoilik** [comment]
Можно скриншот? В переводе этой строки никакой ошибки нет.

**Comment by SPEC1AL1ST** [comment]
Смысл тот, что два раза есть эта строка.
Вот первый раз - https://c2n.me/43isYmt - 8337 строка в All Applications
Вот второй раз - https://c2n.me/43it3gZ - 9801 строка в All Applications

**Comment by ilyahoilik** [comment]
Одна строка для PHP, вторая для JS

**Comment by SPEC1AL1ST** [comment]
> Одна строка для PHP, вторая для JS
А где между ними разница? Как скрипт поймет что для чего?

**Comment by ilyahoilik** [comment]
Разница в атрибуте `js`. На первом скриншоте он `false`, а на втором - `true`.

**Comment by SPEC1AL1ST** [comment]
> Разница в атрибуте `js`. На первом скриншоте он `false`, а на втором - `true`.

Понял! Большое спасибо за пояснение!

**Comment by ilyahoilik** [comment]
Пожалуйста :)
