### ISSUE TITLE
Оставили комментарии (нет пробелов между никами)

### ISSUE THREAD

**Issue by cxemnet** [ilyahoilik/invision-localization#186]
![1278390068_ PNG 77c35bfaa1f13a9357972c6e43f7b4c8 1](https://user-images.githubusercontent.com/5039055/61998368-a11c4900-b0b7-11e9-94a0-1a0e25404b2c.PNG)
Проблема на фото выше. Нет пробелов между никами, и не могу понять как поправить. Пробовал перед %s добавить пробел, но не помогло

**Comment by ilyahoilik** [comment]
@Sipsb у тебя такое есть?

**Comment by Sipsb** [comment]
Нет, не замечал.

**Comment by SPEC1AL1ST** [comment]
Думаю, что это проблема шаблона, а не перевода.

**Comment by ilyahoilik** [comment]
Пока закрою, так как более подробной информации нет.
