### ISSUE TITLE
altcontact_purchases_admin_desc

### ISSUE THREAD

**Issue by Sipsb** [ilyahoilik/invision-localization#188]
Опечатка

> Пользователь сможет просматривать выбранные покупки и запросы в поддержку, связанные с **ними**. Он также сможет связываться с поддержкой с этого аккаунта по проблемам, относящимся к выбранным покупкам.

altcontact_purchases_desc

**Comment by ilyahoilik** [comment]
С ними - с покупками, а не с пользователем. Так что опечатки нет
