### ISSUE TITLE
mod_confirm_all_desc

### ISSUE THREAD

**Issue by SPEC1AL1ST** [ilyahoilik/invision-localization#193]
Чет в этот раз и изменений несколько всего, а ляп на ляпе... Вы хоть вордом перепроверяйте там...

  <word key="mod_confirm_all_desc" js="0">Будут отображаться все публикации, который может просматривать текущий пользователь</word>
Нужно
  <word key="mod_confirm_all_desc" js="0">Будут отображаться все публикации, которые может просматривать текущий пользователь</word>

**Comment by ilyahoilik** [comment]
Сказывается то, что делал перевод уставшим в 3 часа ночи. По клавишам не попадал.
