### ISSUE TITLE
Сортировка

### ISSUE THREAD

**Issue by Sipsb** [ilyahoilik/invision-localization#194]
Сортировка —> Форумов —> Другое.

![2019-09-01_00-55-59](https://user-images.githubusercontent.com/22107941/64069547-434dc480-cc54-11e9-9a3a-0703669db874.png)
![2019-09-01_00-59-17](https://user-images.githubusercontent.com/22107941/64069549-48127880-cc54-11e9-8585-7bb191e29db3.png)
![2019-09-01_00-57-14](https://user-images.githubusercontent.com/22107941/64069548-45b01e80-cc54-11e9-8915-b38b509a5b88.png)

**Comment by ilyahoilik** [comment]
<img width="436" alt="Снимок экрана 2019-10-04 в 2 23 50" src="https://user-images.githubusercontent.com/7265704/66170729-09eee700-e64e-11e9-84d3-17dfb29a31b8.png">
